kind: Deployment
apiVersion: apps/v1
metadata:
   name: gitopstraining
spec:
   replicas: 2
   selector:      # tells the controller which pods to watch/belong to
    matchLabels:
     app: gitopstraining
   template:
      metadata:
        labels:
          app: gitopstraining
      spec:
       containers:
        - name: gitopstraining
          image: sorydiallo89/pipeline-gitops
          imagePullPolicy: Always
          ports:
          - containerPort: 80
