kind: Service                             
apiVersion: v1
metadata:
  name: gitopstraining
  labels:
    app: gitopstraining
spec:
  ports:
    - port: 8080                               
      targetPort: 80                    
      nodePort: 31200
  selector:
    app: gitopstraining                    
  type: NodePort                   
